name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: laravel
            DB_USER: root
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      
    steps:
    - uses: actions/checkout@v3
    
  
    - name: Create Database
      run: mysql --host 127.0.0.1 --port 3306 -uroot -e "CREATE DATABASE IF NOT EXISTS laravel;"
    


    - name: Create Table
      run: mysql --host 127.0.0.1 --port 3306 -uroot -e "CREATE TABLE `users` (
        `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
        `name` varchar(255) NOT NULL,
        `email` varchar(255) NOT NULL,
        `username` varchar(255) NOT NULL,
        `email_verified_at` timestamp NULL DEFAULT NULL,
        `password` varchar(255) NOT NULL,
        `link` varchar(255) DEFAULT NULL,
        `location` varchar(255) DEFAULT NULL,
        `avatar` varchar(255) DEFAULT NULL,
        `remember_token` varchar(100) DEFAULT NULL,
        `created_at` timestamp NULL DEFAULT NULL,
        `updated_at` timestamp NULL DEFAULT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `users_email_unique` (`email`),
        UNIQUE KEY `users_username_unique` (`username`)
        ) ENGINE=InnoDB AUTO_INCREMENT=8636 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"




    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    # mysql -u root
    
    
    - name: Create env
      run: cp .env.example .env
      
    - name: Directory Permissions
      run: chmod -R 777 storage

    - name: Run test suite
      run: vendor/bin/phpunit
