name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    # mysql -u root
    
    
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        #mysql -e 'CREATE DATABASE laravel' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        #mysql -e '-u root'
        #mysql -e 'CREATE DATABASE laravel'
        
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS laravel;'
        
        mysql -e 'CREATE TABLE `users` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) NOT NULL,
          `email` varchar(255) NOT NULL,
          `username` varchar(255) NOT NULL,
          `email_verified_at` timestamp NULL DEFAULT NULL,
          `password` varchar(255) NOT NULL,
          `link` varchar(255) DEFAULT NULL,
          `location` varchar(255) DEFAULT NULL,
          `avatar` varchar(255) DEFAULT NULL,
          `remember_token` varchar(100) DEFAULT NULL,
          `created_at` timestamp NULL DEFAULT NULL,
          `updated_at` timestamp NULL DEFAULT NULL,
          PRIMARY KEY (`id`),
          UNIQUE KEY `users_email_unique` (`email`),
          UNIQUE KEY `users_username_unique` (`username`)
        ) ENGINE=InnoDB AUTO_INCREMENT=8636 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'
        
    - name: Create env
      run: cp .env.example .env
      
    - name: Directory Permissions
      run: chmod -R 777 storage

    - name: Run test suite
      run: vendor/bin/phpunit
